### ISSUE TITLE
Link update on website

### ISSUE THREAD

**Issue by shadiakiki1986** [skybert/my-little-friends#2]
Hey, you need to update the *bash unit testing library* link on your [website](http://skybert.net/bash/unit-testing/) (line 2) to point [here](https://github.com/skybert/my-little-friends/blob/master/bash/common/bash_unit) instead of [here](https://github.com/skybert/my-little-friends/blob/master/bash/bash_unit) after you moved the script into the folder *common*

**Comment by skybert** [comment]
Hi @shadiakiki1986,

I haven't seen your message before now, sorry! I'll have a look at this straight away.

Cheers!

-Torstein

**Comment by skybert** [comment]
Hi again,
I've updated the article now. Thanks again.
-Torstein
